package tema12.temperatura;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Ventana extends javax.swing.JFrame {

    public Ventana() {
        this.setTitle("Conversor de temperaturas");
        initComponents();
        this.setBounds(2500, 200, 500, 400);
        rbCaF.setSelected(true);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                entradaDatos.requestFocusInWindow();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        entradaDatos = new javax.swing.JTextField();
        salidaDatos = new javax.swing.JTextField();
        botConvertir = new javax.swing.JButton();
        rbCaF = new javax.swing.JRadioButton();
        rbFaC = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 51, 255));
        titulo.setText("CONVERSOR DE TEMPERATURAS:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Temperatura en ºCelsius");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Temperatura en ºFahrenheit");

        entradaDatos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        entradaDatos.setMinimumSize(new java.awt.Dimension(1000, 22));
        entradaDatos.setName(""); // NOI18N
        entradaDatos.setPreferredSize(new java.awt.Dimension(100, 22));

        salidaDatos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        salidaDatos.setMinimumSize(new java.awt.Dimension(1000, 22));
        salidaDatos.setName("salidaDatos"); // NOI18N
        salidaDatos.setPreferredSize(new java.awt.Dimension(100, 22));

        botConvertir.setBackground(new java.awt.Color(204, 204, 204));
        botConvertir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botConvertir.setForeground(new java.awt.Color(51, 51, 255));
        botConvertir.setText("Convertir");
        botConvertir.setPreferredSize(new java.awt.Dimension(100, 23));
        botConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConvertirActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCaF);
        rbCaF.setText("Celsius a Fahrenheit");
        rbCaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCaFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbFaC);
        rbFaC.setText("Fahrenheit a Celsius");
        rbFaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFaCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbCaF)
                                .addComponent(jLabel1)
                                .addComponent(rbFaC)))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salidaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titulo))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(rbCaF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbFaC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(entradaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(salidaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConvertirActionPerformed
        double valor = Double.parseDouble(entradaDatos.getText());
        double result = 0;

        if (rbCaF.isSelected()) {
            result = (valor * 9 / 5) + 32;
        } else if (rbFaC.isSelected()) {
            result = (valor - 32) * 5 / 9;
        }

        salidaDatos.setText(String.format("%.2f", result));
    }//GEN-LAST:event_botConvertirActionPerformed

    private void rbFaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFaCActionPerformed
        jLabel1.setText("Temperatura en ºFahrenheit");
        jLabel2.setText("Temperatura en ºCelsius");
    }//GEN-LAST:event_rbFaCActionPerformed

    private void rbCaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCaFActionPerformed
        jLabel1.setText("Temperatura en ºCelsius");
        jLabel2.setText("Temperatura en ºFahrenheit");
    }//GEN-LAST:event_rbCaFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botConvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entradaDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbCaF;
    private javax.swing.JRadioButton rbFaC;
    private javax.swing.JTextField salidaDatos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
